import chromium from "@sparticuz/chromium";
import { marked } from "marked";
import puppeteer from "puppeteer";
import puppeteerCore from "puppeteer-core";
import sanitizeHtml from "sanitize-html";

const CATEGORY_LABELS: Record<string, string> = {
  ai_tech: "AI & Technology Analysis",
  market_research: "Market & Industry Research",
  competitive: "Competitive Analysis",
  business_strategy: "Business Strategy & Planning",
  sales: "Sales Research Brief",
  legal: "Legal Research Brief",
  product: "Product Research Brief",
  operations: "Operations Research Brief",
  custom: "Custom Research Report",
};

export async function generatePDF(
  markdownContent: string,
  title: string,
  category: string,
): Promise<Buffer> {
  const htmlContent = await marked(markdownContent);
  const sanitizedHtmlContent = sanitizeHtml(htmlContent, {
    allowedTags: [
      "h1",
      "h2",
      "h3",
      "h4",
      "h5",
      "h6",
      "p",
      "ul",
      "ol",
      "li",
      "strong",
      "em",
      "blockquote",
      "table",
      "thead",
      "tbody",
      "tr",
      "th",
      "td",
      "code",
      "pre",
      "a",
      "hr",
      "br",
    ],
    allowedAttributes: {
      a: ["href", "title", "target", "rel"],
    },
    allowedSchemes: ["http", "https", "mailto"],
  });

  const currentDate = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const categoryLabel = CATEGORY_LABELS[category] || "Research Report";

  const fullHTML = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');

    * { margin: 0; padding: 0; box-sizing: border-box; }

    body {
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
      font-size: 10.5pt;
      line-height: 1.65;
      color: #1a1a1a;
      padding: 56px 60px;
    }

    .report-header {
      border-bottom: 3px solid #1a56db;
      padding-bottom: 20px;
      margin-bottom: 28px;
    }
    .report-header .brand {
      font-size: 9pt;
      font-weight: 700;
      color: #1a56db;
      letter-spacing: 1.5px;
      text-transform: uppercase;
      margin-bottom: 10px;
    }
    .report-header h1 {
      font-size: 20pt;
      font-weight: 700;
      color: #111;
      line-height: 1.25;
      margin-bottom: 14px;
    }
    .report-header .meta {
      font-size: 8.5pt;
      color: #666;
      display: flex;
      align-items: center;
      gap: 12px;
    }
    .report-header .badge {
      display: inline-block;
      background: #EEF2FF;
      color: #1a56db;
      padding: 3px 10px;
      border-radius: 4px;
      font-size: 8pt;
      font-weight: 600;
    }

    h2 {
      font-size: 14pt;
      font-weight: 700;
      color: #111;
      margin-top: 26px;
      margin-bottom: 10px;
      padding-bottom: 5px;
      border-bottom: 1px solid #e8e8e8;
    }
    h3 {
      font-size: 11.5pt;
      font-weight: 600;
      color: #222;
      margin-top: 18px;
      margin-bottom: 8px;
    }
    p { margin-bottom: 10px; }

    ul, ol {
      margin-bottom: 10px;
      padding-left: 22px;
    }
    li { margin-bottom: 5px; }

    strong { font-weight: 600; }

    blockquote {
      border-left: 3px solid #1a56db;
      padding-left: 14px;
      margin: 14px 0;
      color: #444;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      margin: 14px 0;
      font-size: 9.5pt;
    }
    th, td {
      border: 1px solid #ddd;
      padding: 7px 10px;
      text-align: left;
    }
    th {
      background: #f7f7f7;
      font-weight: 600;
    }

    code {
      background: #f5f5f5;
      padding: 1px 4px;
      border-radius: 3px;
      font-size: 9.5pt;
    }

    .report-footer {
      margin-top: 36px;
      padding-top: 14px;
      border-top: 1px solid #e8e8e8;
      font-size: 7.5pt;
      color: #aaa;
      line-height: 1.5;
    }

    @media print {
      h2 { page-break-after: avoid; }
      .report-header { page-break-after: avoid; }
    }
  </style>
</head>
<body>
  <div class="report-header">
    <div class="brand">BriefGen.ai</div>
    <h1>${escapeHTML(title)}</h1>
    <div class="meta">
      <span class="badge">${categoryLabel}</span>
      <span>Generated ${currentDate}</span>
    </div>
  </div>

  <div class="report-content">
    ${sanitizedHtmlContent}
  </div>

  <div class="report-footer">
    <p>This report was generated by BriefGen.ai using advanced AI research systems.
    While every effort is made to ensure accuracy, this report is for informational
    purposes only and should not be considered professional legal, financial, or medical
    advice. &copy; ${new Date().getFullYear()} BriefGen.ai</p>
  </div>
</body>
</html>`;

  const browser =
    process.env.VERCEL === "1"
      ? await puppeteerCore.launch({
          args: chromium.args,
          defaultViewport: { width: 1280, height: 720 },
          executablePath: await chromium.executablePath(),
          headless: true,
        })
      : await puppeteer.launch({
          headless: true,
          args: ["--no-sandbox", "--disable-setuid-sandbox"],
        });

  try {
    const page = await browser.newPage();
    await page.setJavaScriptEnabled(false);
    await page.setRequestInterception(true);
    page.on("request", (interceptedRequest) => {
      if (
        interceptedRequest.resourceType() === "document" ||
        interceptedRequest.url().startsWith("about:") ||
        interceptedRequest.url().startsWith("data:")
      ) {
        void interceptedRequest.continue();
        return;
      }

      void interceptedRequest.abort();
    });
    await page.setContent(fullHTML, { waitUntil: "networkidle0" });

    const pdfBuffer = await page.pdf({
      format: "Letter",
      printBackground: true,
      margin: { top: "0", right: "0", bottom: "0", left: "0" },
    });

    return Buffer.from(pdfBuffer);
  } finally {
    await browser.close();
  }
}

function escapeHTML(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
